---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadie-sync-techdocs-action
  title: Syncs Techdocs in Roadie Backstage via Github Actions
  annotations:
    github.com/project-slug: roadiehq/sync-techdocs-action
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: RoadieHQ
  lifecycle: production