on: [ pull_request ]

jobs:
  test-sync-techdocs:
    name: Test Sync Techdocs Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build

      - name: Test techdocs-sync action on single-doc catalog-info
        id: test-action-single-doc
        uses: ./
        with:
          catalog-info-path: './catalog-info.yaml'
          api-token: ${{ secrets.ROADIE_ROADIE_API_KEY }}
          backstage-api-endpoint: 'https://api.roadie.so'
          github-token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
      - name: Test techdocs-sync action on multi-doc catalog-info
        id: test-action-multi-doc
        uses: ./
        with:
          catalog-info-path: './catalog-info-test.yaml'
          api-token: ${{ secrets.ROADIE_ROADIE_API_KEY }}
          backstage-api-endpoint: 'https://api.roadie.so'
          github-token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
